### ISSUE TITLE
Cinnamon desktop not supported by Flameshot flatpak

### ISSUE THREAD

**Issue by aplatypus** [flathub/org.flameshot.Flameshot#13]
**Problem**

* I have been using Flamshot for many years on Cinnamon installed on Ubuntu (not using Mint)
* When I decided to move apps to use flatpak Flamshot fails to start:
```
 $ flatpak run org.flameshot.Flameshot
QIBusPlatformInputContext: invalid portal bus.
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:40:46.046: Failed to load module "xapp-gtk3-module"

(flameshot:2): GLib-GIO-ERROR **: 12:40:46.126: Settings schema 'org.cinnamon.desktop.interface' is not installed
```
* Flamshot installed from `apt` works fine under Cinnamon.

**System info**
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

 $ cinnamon --version
Cinnamon 4.8.6

$ flatpak list | grep  flameshot
Flameshot	org.flameshot.Flameshot	11.0.0	stable	system

The missing component does not see to be available:

```
$ flatpak search org.cinnamon.desktop.interface
No matches found
```

**Comment by borgmanJeremy** [comment]
Does this thread help at all?

https://github.com/linuxmint/cinnamon/issues/8239

**Comment by borgmanJeremy** [comment]
FYI we dont really monitor the flathub issue list, so you will have better engagement filing upstream.

**Comment by aplatypus** [comment]
Moved to ...
* https://github.com/flameshot-org/flameshot/issues/2580
