### ISSUE TITLE
Error: None of the authentication protocols specified are supported

### ISSUE THREAD

**Issue by sabriunal** [flathub/org.flameshot.Flameshot#17]
Hi, I can't run flameshot

```
flatpak run org.flameshot.Flameshot 
Gtk-Message: 00:37:35.699: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:37:35.699: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported

```

Flameshot info

```
LC_ALL=C flatpak info org.flameshot.Flameshot 

Flameshot - Powerful and simple to use screenshot software

          ID: org.flameshot.Flameshot
         Ref: app/org.flameshot.Flameshot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 12.1.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 3.6?MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: 8cc7b03ef77af28f019e5698531d5e43208169573055c92566f5c8ff1781670a
      Parent: 93370f9f0ff80f38bf9359229f6a78cfb2abadd46c44c0071f48600050c7c9fd
     Subject: Update v12.0.0.tar.gz to 12.1.0 (16e972b7)
        Date: 2022-07-04 12:13:16 +0000
```

- Window manager: X11
- OS: Ubuntu 22.04.1 LTS x86_64 
- Kernel: 5.15.0-47-generic 
- Packages: 1793 (dpkg), 63 (flatpak) 
- Shell: bash 5.1.16 
- Resolution: 1920x1080, 1920x1080 
- DE: GNOME 42.4 
- WM: Mutter

**Comment by rcalixte** [comment]
@sabriunal Have you tried with additional subcommands? Running it the way you did there, I get the app in my tray (subtle, I know). Launching via the CLI, I get the same exceptions you do but they don't appear to prevent the app from running.

Examples:
```bash
flatpak run org.flameshot.Flameshot --help
flatpak run org.flameshot.Flameshot gui
flatpak run org.flameshot.Flameshot launcher
flatpak run org.flameshot.Flameshot config
```

You should have a .desktop file at `/var/lib/flatpak/exports/share/applications/org.flameshot.Flameshot.desktop` that you can use to launch it as well.

**Comment by sabriunal** [comment]
I have an icon on my shell and have no effect but others work.

desktop file have this command.
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/flameshot org.flameshot.Flameshot
```

**Comment by rcalixte** [comment]
I normally use the context menu and make use of the Desktop Actions available. It may be intentional to keep it minimized in the tray, I'm not sure. I'm glad it's working for you though!

**Comment by rcalixte** [comment]
This is the view from my launcher. Once launched, it stays in the tray and can be activated by a single click. You can also map key bindings directly to the subcommands as well.

![flameshot-taskbar](https://user-images.githubusercontent.com/10281587/212569971-b08b8d49-dd9b-4136-bcb4-bc033f036b0b.png)

**Comment by Arcitec** [comment]
Can confirm: The default action of Flameshot's ".desktop" file is to start running silently in the background. Right-clicking the Desktop shortcut in GNOME Applications will bring up the other actions such as "Configure" and "Take Screenshot".

This behavior comes from Flameshot upstream's own desktop file, so we shouldn't change it just for the Flatpak.

Just educate people more about having to run `flatpak run org.flameshot.Flameshot gui` (which should be manually put by the user in custom OS keybindings, such as in GNOME Settings: Keyboard).

**Comment by rcalixte** [comment]
One more addendum here. Depending on your machine setup or desktop environment's ability to display notifications from Flatpak applications, the default launcher for Flameshot does include a notification when it launches straight to the tray.

![2023-05-31_23-08-25](https://github.com/flathub/org.flameshot.Flameshot/assets/10281587/a88e759b-e623-42c2-8ae7-47f9e29d2805)

**Comment by sabriunal** [comment]
Ok. Let me close. It seem not an error.
