### ISSUE TITLE
Still on v0.8.5 due to compiler error.

### ISSUE THREAD

**Issue by Bananaman** [flathub/org.flameshot.Flameshot#2]
@borgmanJeremy Hi, I noticed that flathub is still on 0.8.5. And I see that it's caused by the latest flatpak commit failing to build:

```
 * [new tag]         v0.9.0                -> v0.9.0
 * [new tag]         v0.9.0.rc1            -> v0.9.0.rc1
 * [new tag]         v0.9.0.rc2            -> v0.9.0.rc2
Failed to download sources: module flameshot: Git commit for branch (null) is 5690afbd4be857e20e0ff6f100c890a7250cccfe, but expected 856e08a019b8e9adc9f92ca24380940492ad172c
program finished with exit code 1
elapsedTime=5.807701
```

https://github.com/flathub/org.flameshot.Flameshot/commit/cbf0daacd0e5eaa7245878e60957f40e044bfecd

Try to remove the "commit" rule and build based on release tag instead, since flameshot clearly force-pushes and overwrites their own tags periodically to point at other commits.

**Comment by borgmanJeremy** [comment]
Thanks for pointing this out. I don't usually force push over tags on the main repo so I just fixed the SHA in this case. Can you show me where the build is failing so I can check that my change fixed it?

**Comment by Bananaman** [comment]
@borgmanJeremy Oh, I didn't notice that you're part of the official flameshot project. Awesome. Thanks for making a flatpak! :)

And glad you found the CI log. I saw it on the https://github.com/flathub/org.flameshot.Flameshot/commits/master page by clicking on the red "X" at the latest commit.

Well, thank you very much for fixing it! Awesome! ❤️
