### ISSUE TITLE
Closes immediately

### ISSUE THREAD

**Issue by Yajo** [flathub/org.flameshot.Flameshot#6]
Since a recent update, I run `flatpak run org.flameshot.Flameshot gui` and then Flameshot opens for a second and dies immediately:

https://user-images.githubusercontent.com/973709/126946033-0bbcf33c-e39d-4f87-a5e2-86b0b07681f9.mp4

**Comment by Yajo** [comment]
Oh I can see it got fixed in latest flameshot. Maybe you can update it?
https://github.com/flameshot-org/flameshot/releases/tag/v0.10.1

**Comment by tinywrkb** [comment]
You can try the test build from #5.

**Comment by Dansito** [comment]
The same thing happens to me in arch linux, any solution? :cry:

**Comment by borgmanJeremy** [comment]
@Dansito  did you try with the test build?

**Comment by Dansito** [comment]
No, but i guess flameshot in repositories of arch, It should be the latest version

**Comment by tinywrkb** [comment]
> No, but i guess flameshot in repositories of arch, It should be the latest version

You're guessing wrong, and this is the Flathub package, it got nothing to do with the Arch's package,

**Comment by Dansito** [comment]
The same thing happens to me as the friend in the video, as soon as I open flameshot gui it closes suddenly, it is solved by deleting the config, but I restart the pc and the same thing happens to me again...

**Comment by borgmanJeremy** [comment]
You need to use the new version 0.10.1. The package will eventually be updated in flathub, all merging is complete.
