### ISSUE TITLE
Fedora 34/Gnome/Wayland doesn't work.

### ISSUE THREAD

**Issue by leehambley** [flathub/org.flameshot.Flameshot#7]
Filed upstream (in error, apparently) at https://github.com/flameshot-org/flameshot/issues/1769#issuecomment-887286493

Direct from `dnf` works (https://src.fedoraproject.org/rpms/flameshot) so this seems to be a Flatpak distribution problem.

Would not be so serious, except that the Fedora software center prefers the Flatpak over the rpm, so people will get a bad experience by default unless installing via CLI.

**Comment by borgmanJeremy** [comment]
Fix upstream and just published the fix on flatpak
