### ISSUE TITLE
Flameshot is out of date

### ISSUE THREAD

**Issue by dginovker** [flathub/org.flameshot.Flameshot#9]
Hi Flameshot maintainers -

When launching Flameshot, it prompts to upgrade to `0.10.2`. I can't take a screenshot since it's my screenshot software that's saying this :zany_face: 

Current Flathub version is `0.10.1`

**Comment by dginovker** [comment]
Related to #8

**Comment by borgmanJeremy** [comment]
i just merged the new version.

**Comment by Yajo** [comment]
Weird. Code points to 0.10.2, but in the store the latest version is still 0.10.1:

![imagen](https://user-images.githubusercontent.com/973709/145786073-a2cd143b-1874-4b1b-a8df-b98c18b9b7d0.png)

What's happening? I need 0.10.2 for the fix in https://github.com/flameshot-org/flameshot/issues/1910#issuecomment-967449170 😕

**Comment by tinywrkb** [comment]
Something is wrong with the upstream source.  
If you check out the v0.10.2 tag locally, that's [2bf8a92e700781a36d2cd85d3c34dc275edf28a6](https://github.com/flameshot-org/flameshot/commit/2bf8a92e700781a36d2cd85d3c34dc275edf28a6), then `FLAMESHOT_VERSION` in `CMakeLists.txt` is still `0.10.1`, and similarly the appdata is outdated.
